### ISSUE TITLE
Doesn't work the Python sample on Ubuntu on WSL2

### ISSUE THREAD

**Issue by korguchi** [DwangoMediaVillage/pydomino#2]
I encountered an issue while trying the run sample of Python script on Ubuntu 22.04 on WSL2. 

The script:
```
y = librosa.load('./a.wav', sr=16_000, mono=True, dtype=np.float32)[0]
p = ['pau', 'k', 'o', 'N', 'n', 'i', 'ch', 'i', 'w', 'a', 'pau']
z = alignmer.align(y, " ".join(p), N=3)
```

The error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: align(): incompatible function arguments. The following argument types are supported:
    1. (self: pydomino.Aligner, arg0: numpy.ndarray[numpy.float32[m, 1], flags.writeable], arg1: str, arg2: int) -> list[tuple[float, float, str]]

Invoked with: <pydomino.Aligner object at 0x7ff923f3e230>, array([-0.01690674, -0.02380371, -0.02584839, ..., -0.03399658,
       -0.02627563, -0.02682495], dtype=float32), 'pau k o N n i ch i w a pau'; kwargs: N=3
```

It seems that the align function is not accepting the provided numpy array and string arguments correctly. This might be related to a type conversion issue in pybind11.

Could you please look into this issue and provide advice on how to resolve it?

Thank you for your assistance.

**Comment by ueshunJP** [comment]
Thanks for submitting the issue and sorry for the late responding.
This problem is resolved by not using keyword arguments in aligner.align function. Like this

```python
y = librosa.load('./a.wav', sr=16_000, mono=True, dtype=np.float32)[0]
p = ['pau', 'k', 'o', 'N', 'n', 'i', 'ch', 'i', 'w', 'a', 'pau']
z = alignmer.align(y, " ".join(p), 3)
```

I will update example in README.md soon.

**Comment by korguchi** [comment]
I'm sorry for the delayed response too. I confirm it is working. I appreciate fixing it and releasing such a great model!
